server:
  servlet:
    context-path: /
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://home.yakimovvn.ru:5432/hadoopprj?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: vladimir
    password: Bhbyf>hnftdf2011
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
  flyway:
    locations: classpath:/db/migration